### PR TITLE
Add a readme file

### PR DESCRIPTION
**Pull request by notwaldorf**
I've copy pasted/slightly formatted the contents of `lsaddr.1.txt`. I know duplication is bad, but I thought a readme might be friendlier to newbies (me) who don't know where to look for `man` pages. 🐼

### CODE REVIEW

**Comment by kamalmarhubi** [comment]
Could you `ln -s lsaddr.1.txt README.adoc` instead?

**Comment by kamalmarhubi** [comment]
I'll do it myself then! :-1:

**Comment by kamalmarhubi** [comment]
;-)

**Comment by notwaldorf** [comment]
Just saying, my `readme` was waaaaay prettier 😛

**Pull request closed without merging**
